### ISSUE TITLE
How to use the actual version?

### ISSUE THREAD

**Issue by b1thvngg** [fjqisba/VmpHelper#1]
Hey there, thanks for the interesting project. 
Is there any instructions how to compile the newest version of the project?

As far as I understand, you use IDA 7.5 + corresponding SDK. I have same Ida, also compiled sources (including missing capstone and unicorn .lib files)
dropped Revampire inside plugins directory and got this:

LoadLibrary(C:\Users\Usr\Desktop\ida_75\IDA\plugins\Revampire.dll) error: The specified module could not be found.
C:\Users\Usr\Desktop\ida_75\IDA\plugins\Revampire.dll: can't load file

The reason why I'm trying to build latest sources is that I have the following issue for the last release:
![image](https://github.com/fjqisba/VmpHelper/assets/101625218/fc4d0f3d-73a1-4f38-be5f-569647075a1e)

In reality there should be a conditional jump inside two different blocks, but graph does not recognize it

Thank you :)

**Comment by fjqisba** [comment]
In fact, there is an old code, but it is very messy. I'm porting old code while thinking about new code.
It takes time for the plugin to support vm branches.

**Comment by b1thvngg** [comment]
yeah, got it
Can you please tell which version of IDA, capstone and unicorn you use for debugging?

**Comment by fjqisba** [comment]
The IDA version is 7.5.
As for capstone and unicorn,Just pick a recent version and it should ok，btw, you must match the versions of the include and lib files.

**Comment by fjqisba** [comment]
Now I have added the code related to branch prediction, you can refer to it.
It should be noted that if you want to predict vm branches, you must be able to identify all handlers of vmp. However, the current source code only supports the identification of a small number of handlers, so you may fail in the analysis.
