### ISSUE TITLE
IDA8.3 support

### ISSUE THREAD

**Issue by greenozon** [fjqisba/VmpHelper#2]
Thanks for your efforts
I'm trying to bring-up the plugin in the 8.3 env
so far so good but one issue is blocking:

![image](https://github.com/fjqisba/VmpHelper/assets/765343/aed53f0b-8aa4-4199-a9b1-452201160b8b)

Looks like the token `grcode_user_gentext`  was removed in IDA starting from version 7.6
well, not actually removed but renamed:

![image](https://github.com/fjqisba/VmpHelper/assets/765343/896c9f3f-1be1-40a3-8d5e-1b0bfd38d040)

grcode_user_gentext  ---> grcode_reserved2 ?

but the question is whether IDA injects this notification in new versions, as comments were removed...

**Comment by greenozon** [comment]
Another issue hit:

![image](https://github.com/fjqisba/VmpHelper/assets/765343/10cd90f5-e963-4401-8b7f-84c1ec6bd684)


not sure if you need this var at all?
Looks like it has 0 references, so could be freely removed

**Comment by fjqisba** [comment]
Both codes are correct but one is ida7.5 and the other is ida 8.3.
since ida 8.3 has been leaked, I decided to drop 7.5

**Comment by greenozon** [comment]
thanks for fast reply!
maybe it makes sense to wrap that enum into #ifdef ?
